export const catalog = [
  {
    itemID: 1,
    inputs: [],
    outputs: [],
    itemType: 'compute',
    NodeType: 'itemNode',
    price: '2.82',
    icon: '../../Images/Compute.png',
    configuration: '1 vCPU, 1 GiB RAM',
    name: 'Small Compute',
    Destination: 'Azure',
    OwnerApplication: 'TBD',
    color: 'yellow',
    scriptPath: '/virtual-machines/linux/basic-password'
  },
  {
    itemID: 2,
    inputs: [],
    outputs: [],
    itemType: 'compute',
    NodeType: 'itemNode',
    price: '25.45',
    icon: '../../Images/Compute.png',
    configuration: '2 vCPU, 4 GiB RAM',
    name: 'Medium Compute',
    Destination: 'Azure',
    OwnerApplication: 'TBD',
    color: 'yellow',
    scriptPath: '/virtual-machines/linux/basic-password'
  },
  {
    itemID: 3,
    inputs: [],
    outputs: [],
    itemType: 'compute',
    NodeType: 'itemNode',
    price: '30.43',
    icon: '../../Images/Compute.png',
    configuration: '4 vCPU, 16 GiB RAM',
    name: 'Large Compute',
    Destination: 'Azure',
    OwnerApplication: 'TBD',
    color: 'yellow',
    scriptPath: '/virtual-machines/linux/basic-password'
  },
  {
    itemID: 4,
    inputs: [],
    outputs: [],
    itemType: 'storage',
    NodeType: 'itemNode',
    price: '34.54',
    icon: '../../Images/Storage.png',
    configuration: 'DiskSize S30 Capacity 1024',
    name: 'Regular Storage',
    Destination: 'Azure',
    OwnerApplication: 'TBD',
    scriptPath: '/storage/storage-share'
  },
  {
    itemID: 5,
    inputs: [],
    outputs: [],
    itemType: 'storage',
    NodeType: 'itemNode',
    price: '119.82',
    icon: '../../Images/Storage.png',
    configuration: 'DiskSize P30 Capacity 8192',
    name: 'Premium Storage',
    Destination: 'Azure',
    OwnerApplication: 'TBD',
    scriptPath: '/storage/storage-share'
  },
  {
    itemID: 6,
    inputs: [],
    outputs: [],
    itemType: 'database',
    NodeType: 'itemNode',
    price: '100.82',
    icon: '../../Images/Database.png',
    configuration: 'DiskSize P30 Capacity 8192',
    name: 'Cassandra',
    Destination: 'Azure',
    OwnerApplication: 'TBD',
    scriptPath: '/storage/storage-share'
  },
  {
    itemID: 7,
    inputs: [],
    outputs: [],
    itemType: 'database',
    NodeType: 'itemNode',
    price: '201.64',
    icon: '../../Images/Database.png',
    configuration: 'DiskSize P30 Capacity 8192',
    name: 'Cassandra HA',
    Destination: 'Azure',
    OwnerApplication: 'TBD',
    scriptPath: '/storage/storage-share'
  },
  {
    itemID: 8,
    inputs: [],
    outputs: [],
    itemType: 'database',
    NodeType: 'itemNode',
    price: '239.99',
    icon: '../../Images/Database.png',
    configuration: 'Gen5 Series 2 vCore 10.2 GB RAM. Storage: 5 GB-4 TB',
    name: 'MS SQL Server',
    Destination: 'Azure',
    OwnerApplication: 'TBD',
    scriptPath: '/storage/storage-share'
  },
  {
    itemID: 9,
    inputs: [],
    outputs: [],
    itemType: 'database',
    NodeType: 'itemNode',
    price: '201.64',
    icon: '../../Images/Database.png',
    configuration: 'DiskSize P30 Capacity 8192',
    name: 'MySQL',
    Destination: 'Azure',
    OwnerApplication: 'TBD',
    scriptPath: '/storage/storage-share'
  },
  {
    itemID: 10,
    inputs: [],
    outputs: [],
    itemType: 'database',
    NodeType: 'itemNode',
    price: '201.64',
    icon: '../../Images/Database.png',
    configuration: 'DiskSize P30 Capacity 8192',
    name: 'Oracle',
    Destination: 'Azure',
    OwnerApplication: 'TBD',
    scriptPath: '/storage/storage-share'
  },
  {
    itemID: 11,
    inputs: [],
    outputs: [],
    itemType: 'MessageQueue',
    NodeType: 'itemNode',
    price: '21.64',
    icon: '../../Images/Queue.png',
    configuration: 'Throughput unit (1 MB/s ingress, 2 MB/s egress)',
    name: 'Kafka Topic',
    Destination: 'Azure',
    OwnerApplication: 'TBD',
    scriptPath: '/storage/storage-share'
  },
  {
    itemID: 12,
    inputs: [],
    outputs: [],
    itemType: 'MessageQueue',
    NodeType: 'itemNode',
    price: '5560.41',
    icon: '../../Images/Queue.png',
    configuration: '1.05 GB/sec - Ingress 250 TUs',
    name: 'Premium Event Hub',
    Destination: 'Azure',
    OwnerApplication: 'TBD',
    scriptPath: '/storage/storage-share'
  },
  {
    itemID: 13,
    inputs: [],
    outputs: [],
    itemType: 'MessageQueue',
    NodeType: 'itemNode',
    price: '21.64',
    icon: '../../Images/Queue.png',
    configuration: 'Throughput unit (1 MB/s ingress, 2 MB/s egress)',
    name: 'RabbitMQ Topic',
    Destination: 'Azure',
    OwnerApplication: 'TBD',
    scriptPath: '/storage/storage-share'
  },
  {
    itemID: 14,
    inputs: [],
    outputs: [],
    itemType: 'function',

    NodeType: 'itemNode',
    price: '17.60',
    icon: '../../Images/AppFunctions.png',
    configuration: '3 million sec, 1.5 million GB-s, ',
    name: 'AppFunction',
    Destination: 'Azure',
    OwnerApplication: 'TBD',
    scriptPath: '/app-service/function-basic'
  },
  {
    itemID: 15,
    inputs: [],
    outputs: [],
    itemType: 'compute',
    NodeType: 'itemNode',
    price: '201.64',
    icon: '../../Images/Queue.png',
    configuration: 'DiskSize P30 Capacity 8192',
    name: 'Container',
    Destination: 'Azure',
    OwnerApplication: 'TBD',
    scriptPath: '/Container/Container'
  },
  {
    itemID: 16,
    inputs: [],
    outputs: [],
    itemType: 'MessageQueue',
    NodeType: 'itemNode',
    price: '201.64',
    icon: '../../Images/Queue.png',
    configuration: 'DiskSize P30 Capacity 8192',
    name: 'Kafka Topic',
    Destination: 'Azure',
    OwnerApplication: 'TBD',
    scriptPath: '/MessageQ/MessageQ-Simple'
  }
];
